<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
    <?php require VIEWS_PATH . '/includes/messages.phtml';?>

    <div class="jumbotron">
        <h1>Loja Virtual</h1>
        <p>
            Projeto Loja Virtual - Auto Fornecedor
        </p>
        <p>
            <a class="btn btn-lg btn-primary" href="http://bit.ly/ce-learn" role="button">Saiba mais &raquo;</a>
        </p>
    </div>

    <div class="row">
       
    </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
